name: FXTI
favicon: null
layout_spectrum: 0.4992428128607571
typography_spectrum: 0.6080346263479441
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#084d90'
    - '#d0dde9'
    - '#4d7eae'
    - '#9ab6d0'
  brandStrength: 0.6875
  lightness: 0.7634320561774075
  saturation: 0.31352383317425847
  rhythmicContrast: 0.20656688720919192
purpose: []
